AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Template to create infraestructure as code

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Resources:
  HelloWorld1000746182:
    Type: AWS::Serverless::Function # this means that is going to be a lamda function
    Properties:
      CodeUri: hello_world/ # Where is the code of the lamda function
      Handler: app.lambda_handler # Where is the controller
      Runtime: python3.8
      Architectures:
        - x86_64
      Events:
        HelloWorld: # Events name
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /test # Route
            Method: get # Method
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DynamoDBTable
  DynamoDBTable:
    Type: 'AWS::Serverless::SimpleTable'
    Properties:
      TableName: sam-table-1000746182


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorld1000746182.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorld1000746182Role.Arn
